"""
Define all api v1 related constants here.
"""

API_DEFAULT_ERROR_CODE = 1000
UNAUTHORIZED_USER_CODE = 1001
FORBIDDEN_ACTION_CODE = 1002
AUTH_BASE_EXCEPTION_CODE = 1003
FIELD_REQUIRED_ERROR_CODE = 1004
FIELD_BLANK_ERROR_CODE = 1005
FIELD_NULL_ERROR_CODE = 1006
FIELD_INVALID_ERROR_CODE = 1007
INTERNAL_ERROR_CODE = 1008
INVALID_REQUEST_TOKEN_CODE = 1009
INVALID_OTP_CODE = 1010

FIELD_REQUIRED_ERROR_MSG = "{entity} field is required."
FIELD_BLANK_ERROR_MSG = "{entity} field may not be blank."
FIELD_NULL_ERROR_MSG = "{entity} field may not be null."
FIELD_INVALID_ERROR_MSG = "{entity} value is invalid."
